### ISSUE TITLE
Bug: Application Details Page - Select Menu Not Showing

### ISSUE THREAD

**Issue by alvintangz** [hackthevalley/hack-the-back-admin#11]
In production, go to https://admin.hackthevalley.io/apps/b663601d-92b3-4847-8d6e-282aac7c5ecd.

You'll see that questions with the select type don't properly show answers.

![image](https://user-images.githubusercontent.com/5105156/143783217-1363e001-0bc3-4879-a8df-c9dc50fb9042.png)

**Comment by Cptmoomoo** [comment]
resolved
