### ISSUE TITLE
Home Page `/`

### ISSUE THREAD

**Issue by fpunny** [hackthevalley/hack-the-back-admin#4]
## Overview
The Home with high level stat boxes

## Requirements
 - Able to see number of users and their types
 - Able to see number of hacker applications

## Note
 - If you want, stick in graphs - that would be cool. I suggest using apexcharts since they work well (You can look into others, if you can use D3 in a maintainable manner then I'll literally refer you into my work right now)
 - Try to keep each "stat" as it's own little module. It would help with us making this modular and easy to change. (It would also help us do cool stuff given we have the time)

**Comment by Manpreet-Bhatti** [comment]
- [ ] Number of users and their types
- [ ] Number of hacker applications

**Comment by Manpreet-Bhatti** [comment]
@fpunny for the types of users, are you asking for whether they're staff or not? Or is it a question of whether the user has been accepted, rejected, etc.?

**Comment by fpunny** [comment]
We can do both owo

**Comment by Manpreet-Bhatti** [comment]
@fpunny hey Fred, should we be using any certain colours for colouring the data plots on a graph?

**Comment by fpunny** [comment]
> @fpunny hey Fred, should we be using any certain colours for colouring the data plots on a graph? Or maybe a predefined palette I could possibly use?
> 
> Ended up setting up colours I found from HTV site -- hope that's ok for now.

Thats works :3
